import type { MetadataRoute } from "next";

// Web app manifest → makes TaskMOS installable (Android/desktop Chrome "Install",
// iOS "Add to Home Screen") and opens it full-screen standalone like a native
// app. No service worker / offline caching by design. Next auto-injects
// <link rel="manifest" href="/manifest.webmanifest"> from this file.
// Icons are generated by app/icon-192.png + app/icon-512.png + app/apple-icon.tsx.
export default function manifest(): MetadataRoute.Manifest {
  return {
    name: "TaskMOS — Organic Social Media Growth",
    short_name: "TaskMOS",
    description:
      "Earn points by engaging with real creators, then spend them to grow your own content — 100% organic, no bots.",
    start_url: "/dashboard",
    scope: "/",
    display: "standalone",
    orientation: "portrait",
    background_color: "#ffffff",
    theme_color: "#9333ea",
    categories: ["social", "productivity", "marketing"],
    icons: [
      { src: "/icon-192.png", sizes: "192x192", type: "image/png", purpose: "any" },
      { src: "/icon-512.png", sizes: "512x512", type: "image/png", purpose: "any" },
      { src: "/icon-512.png", sizes: "512x512", type: "image/png", purpose: "maskable" },
    ],
  };
}
